### ISSUE TITLE
Error when loading the model naip_demo

### ISSUE THREAD

**Issue by olivier-gillet** [microsoft/landcover#10]
Hi,
We I click on "Start Server" selecting the NAIP Supervised mode, an error occurs.
It seems that the model cannot be correctly loaded.
Do you have any idea where does it comes from ?
Thanks!

```
2020-03-26 09:13:58,997 - WARNING - Haven't connected, attempt 1
XXX lineno: 197, opcode: 0
Traceback (most recent call last):
  File "web_tool/worker.py", line 91, in <module>
    main()
  File "web_tool/worker.py", line 83, in main
    model = KerasDenseFineTune(args.model_fn, args.gpuid, args.fine_tune_layer, args.fine_tune_seed_data_fn)
  File "/home/olgill/landcover/web_tool/ServerModelsKerasDense.py", line 36, in __init__
    "loss":keras.metrics.mean_squared_error
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 906, in from_config
    config, custom_objects)
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1852, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1799, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/olgill/anaconda3/envs/ai4e/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/core.py", line 795, in call
    return self.function(inputs, **arguments)
  File "/mnt/afs/code/land-cover-mapping-training/models.py", line 197, in <lambda>
SystemError: unknown opcode
```

**Comment by calebrob6** [comment]
Hi @olivier-gillet, the setup instructions should be a bit more stable now. If you try the README you should get correct results for the demo models.
